# Setup and build the client
FROM node:16-alpine as client-build
WORKDIR /usr/app/
COPY package*.json ./
RUN npm install -qy
COPY . .
RUN npm run build

# Setup the server
FROM nginx:1.15-alpine
COPY nginx.conf /etc/nginx/nginx.conf
WORKDIR /usr/app/
COPY --from=client-build /usr/app/build/ .

EXPOSE 80
